#ifndef WARSPIDER_VERSION_H
#define WARSPIDER_VERSION_H

#define WAR_SPIDER_VERSION_MAJOR 0
#define WAR_SPIDER_VERSION_MINOR 0
#define WAR_SPIDER_VERSION_PATCH 8

#define WAR_SPIDER_VERSION_STRING "0.0.8"

#endif